package java_projet;

import java.sql.*;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yavuix
 */
public class fenetre_principale extends javax.swing.JFrame {

    /**
     * Creates new form fenetre_principale
     */
    public fenetre_principale() {
        initComponents();
        //getConnection();
        montrer_produits_dans_JTable();
    }
    
    String ImgPath = null;
    int pos = 0; 
            
    public Connection getConnection() 
    {
        Connection con = null;
        
         
        try {
            con = DriverManager.getConnection("jdbc:mysql://89.234.180.28:3306/w9no2p_Yav", "w9no2p_Yav", "yavtestbdd");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(fenetre_principale.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        } 
    }
    // verifier champ "insérer"
    public boolean checkInputs()
    {
        if(
                txt_nom.getText() == null
             || txt_prix.getText() == null
                ){ 
            return false;
        }else{
            try{
                Float.parseFloat(txt_prix.getText());
                return true;
            }catch(Exception ex)
            {
                return false;
            }
        }
    }
   
    
    //Redimmensioner image
    public ImageIcon ResizeImage(String imagePath, byte [] pic)
    {
        ImageIcon myImage = null;
        
        if(imagePath != null)
        {
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(label_image.getWidth(), label_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    
    //afficher les données dans la JTable
    // 1 -- remplir la ArrayList avec les données
    
    public ArrayList<Produit> getProductList()
    {
            ArrayList<Produit> produitList = new ArrayList<Produit>();
            Connection con = getConnection();
            String query = "SELECT * FROM produits";
            
            Statement st;
            ResultSet rs;
        try {
           
            st = con.createStatement();
            rs = st.executeQuery(query);
            Produit produit;
            
            while(rs.next())
            {
                produit = new Produit(rs.getInt("id"),rs.getString("nom"), Float.parseFloat(rs.getString("prix")),rs.getBytes("image"),rs.getInt("quantite"));
                produitList.add(produit);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(fenetre_principale.class.getName()).log(Level.SEVERE, null, ex);
        }
        return produitList;
    }
    
    
    // 2 -- Populer la JTable
    
    public void montrer_produits_dans_JTable()
    {
        ArrayList<Produit> list = getProductList();
        DefaultTableModel model = (DefaultTableModel)JTable_Produits.getModel();
        // Effacer le contenu de la JTable
        model.setRowCount(0);
        Object[] row = new Object [4];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getNom();
            row[2] = list.get(i).getPrix();
            row[3] = list.get(i).getQuantite();
            
            model.addRow(row);
        }
    }
    
    public void ShowItem(int index)
    {
        txt_id.setText(Integer.toString(getProductList().get(index).getId()));
        txt_nom.setText(getProductList().get(index).getNom());
        txt_prix.setText(Float.toString(getProductList().get(index).getPrix()));
        label_image.setIcon(ResizeImage(null, getProductList().get(index).getimage()));
        txt_quantite.setText(Integer.toString(getProductList().get(index).getQuantite()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_prix = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        label_image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Produits = new javax.swing.JTable();
        btn_choisir_image = new javax.swing.JButton();
        btn_maj = new javax.swing.JButton();
        btn_ajouter = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        btn_debut = new javax.swing.JButton();
        btn_precedent = new javax.swing.JButton();
        btn_suivant = new javax.swing.JButton();
        btn_fin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_quantite = new javax.swing.JTextField();
        txt_somme = new javax.swing.JTextField();
        btn_somme = new javax.swing.JButton();

        jButton3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_projet/inserer.png"))); // NOI18N
        jButton3.setText("Insérer");
        jButton3.setIconTextGap(15);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Image :");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Prix :");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Nom :");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("ID : ");

        txt_id.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_id.setEnabled(false);
        txt_id.setPreferredSize(new java.awt.Dimension(59, 50));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_prix.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_prix.setPreferredSize(new java.awt.Dimension(59, 50));
        txt_prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prixActionPerformed(evt);
            }
        });

        txt_nom.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_nom.setPreferredSize(new java.awt.Dimension(59, 50));
        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });

        label_image.setBackground(new java.awt.Color(204, 255, 255));
        label_image.setOpaque(true);

        JTable_Produits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Prix", "Quantite"
            }
        ));
        JTable_Produits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_ProduitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_Produits);

        btn_choisir_image.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btn_choisir_image.setText("Choisir l'image");
        btn_choisir_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choisir_imageActionPerformed(evt);
            }
        });

        btn_maj.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btn_maj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_projet/maj.png"))); // NOI18N
        btn_maj.setText("Mettre à Jour");
        btn_maj.setIconTextGap(15);
        btn_maj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_majActionPerformed(evt);
            }
        });

        btn_ajouter.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btn_ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_projet/inserer.png"))); // NOI18N
        btn_ajouter.setText("Insérer");
        btn_ajouter.setIconTextGap(15);
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });

        btn_supprimer.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btn_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_projet/supprimer.png"))); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.setIconTextGap(15);
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        btn_debut.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btn_debut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_projet/debut.png"))); // NOI18N
        btn_debut.setText("Début");
        btn_debut.setIconTextGap(15);
        btn_debut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_debutActionPerformed(evt);
            }
        });

        btn_precedent.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btn_precedent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_projet/precedent.png"))); // NOI18N
        btn_precedent.setText("Précédent");
        btn_precedent.setIconTextGap(15);
        btn_precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_precedentActionPerformed(evt);
            }
        });

        btn_suivant.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btn_suivant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_projet/suivant.png"))); // NOI18N
        btn_suivant.setText("Suivant");
        btn_suivant.setIconTextGap(15);
        btn_suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suivantActionPerformed(evt);
            }
        });

        btn_fin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btn_fin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_projet/fin.png"))); // NOI18N
        btn_fin.setText("Fin");
        btn_fin.setIconTextGap(15);
        btn_fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Quantité :");

        txt_quantite.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_quantite.setPreferredSize(new java.awt.Dimension(59, 50));
        txt_quantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantiteActionPerformed(evt);
            }
        });

        txt_somme.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_somme.setPreferredSize(new java.awt.Dimension(59, 50));
        txt_somme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sommeActionPerformed(evt);
            }
        });

        btn_somme.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btn_somme.setText("Avoir la quantité :");
        btn_somme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sommeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_choisir_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_prix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_quantite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_ajouter)
                                .addGap(18, 18, 18)
                                .addComponent(btn_maj))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_somme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_somme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_supprimer))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_debut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_precedent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_suivant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fin))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_choisir_image))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_maj, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_debut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_precedent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suivant, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_somme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_somme))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prixActionPerformed

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void btn_choisir_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choisir_imageActionPerformed
       JFileChooser file = new JFileChooser();
       file.setCurrentDirectory(new File(System.getProperty("user.home")));
       
       FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image", "jpg", "png");
       file.addChoosableFileFilter(filter);
       int result = file.showSaveDialog(null);
       if (result == JFileChooser.APPROVE_OPTION)
       {
           File selectedFile = file.getSelectedFile();
           String path = selectedFile.getAbsolutePath();
           label_image.setIcon(ResizeImage(path, null));
           ImgPath = path;
       }
       else{
           System.out.println("Aucun fichier selectionné");
       }
    }//GEN-LAST:event_btn_choisir_imageActionPerformed

    private void btn_majActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_majActionPerformed
        if(checkInputs() && txt_id.getText() != null)
        {
            String UpdateQuery = null;
            PreparedStatement ps = null;
            Connection con = getConnection();
            
            //mise a jour sans l'image
            if(ImgPath == null)
            {
                try {
                    UpdateQuery = "UPDATE produits SET nom = ?, prix = ?, quantite = ? WHERE id = ?";
                    
                    ps = con.prepareStatement(UpdateQuery);
                    ps.setString(1, txt_nom.getText());
                    ps.setString(2, txt_prix.getText());
                    ps.setString(3, txt_quantite.getText());
                    ps.setInt(4, Integer.parseInt(txt_id.getText()));
                    ps.executeUpdate(); //executer la maj
                    montrer_produits_dans_JTable();
                    JOptionPane.showMessageDialog(null, "Produit mis à jour");
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(fenetre_principale.class.getName()).log(Level.SEVERE, null, ex);
                }
             // MAJ Avec L'image   
            }else{
                try{
                InputStream img = new FileInputStream(new File(ImgPath));
                
                UpdateQuery = "UPDATE produits SET nom = ?, prix = ?, quantite = ?,"+" image = ? WHERE id = ?";
                
                    ps = con.prepareStatement(UpdateQuery);
                    ps.setString(1, txt_nom.getText());
                    ps.setString(2, txt_prix.getText());
                    ps.setString(3, txt_quantite.getText());
                    ps.setBlob(4,img);
                    ps.setInt(5, Integer.parseInt(txt_id.getText()));
                    
                    ps.executeUpdate(); //executer la maj
                    montrer_produits_dans_JTable();
                    JOptionPane.showMessageDialog(null, "Produit mis à jour");
                
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            }  
        }else{
            JOptionPane.showMessageDialog(null, "1 ou Plusieurs champs manquants ou incorrects");
        }
    }//GEN-LAST:event_btn_majActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        if(checkInputs() && ImgPath != null)
        {  
            try {
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO produits(nom,prix,image,quantite)"+ "values(?,?,?,?)");
                ps.setString(1, txt_nom.getText());
                ps.setString(2, txt_prix.getText());
                InputStream img = new FileInputStream(new File(ImgPath));
                ps.setBlob(3, img);
                ps.setString(4, txt_quantite.getText());
                ps.executeUpdate();
                montrer_produits_dans_JTable();
                
                JOptionPane.showMessageDialog(null, "Produit inséré");
                
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "1 ou Plusieurs champs sont vides");
        }
        
        
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        if(!txt_id.getText().equals(""))
        {
            try {
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("DELETE FROM produits WHERE id = ?");
                int id = Integer.parseInt(txt_id.getText());
                ps.setInt(1, id);
                ps.executeUpdate();
                montrer_produits_dans_JTable();
                JOptionPane.showMessageDialog(null, "Produit supprimé");
            } catch (SQLException ex) {
                Logger.getLogger(fenetre_principale.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Erreur : Produit non supprimé");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Erreur : Produit non supprimé, pas d'ID à supprimer");
        }
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_debutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_debutActionPerformed
       pos = 0;
       ShowItem(pos);
    }//GEN-LAST:event_btn_debutActionPerformed

    private void btn_precedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_precedentActionPerformed
       pos--;
       
       if(pos < 0)
       {
           pos=0;
       }
       ShowItem(pos);
    }//GEN-LAST:event_btn_precedentActionPerformed

    private void btn_suivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suivantActionPerformed
        pos++;
        
        if(pos >= getProductList().size())
        {
            pos = getProductList().size()-1;
        }
        ShowItem(pos);
    }//GEN-LAST:event_btn_suivantActionPerformed

    private void btn_finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finActionPerformed
        pos = getProductList().size()-1;
        ShowItem(pos);
    }//GEN-LAST:event_btn_finActionPerformed

    private void JTable_ProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_ProduitsMouseClicked
        int index = JTable_Produits.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_JTable_ProduitsMouseClicked

    private void txt_quantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantiteActionPerformed

    private void txt_sommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sommeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sommeActionPerformed

    private void btn_sommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sommeActionPerformed
    try {
        String sql="SELECT sum(quantite) FROM produits";
        Connection con = getConnection();
          PreparedStatement ps = con.prepareStatement(sql);
                
    
            
            Statement st;
            ResultSet rs;
            
        
           
            st = con.createStatement();
            rs=ps.executeQuery();
      
                if(rs.next()){
                    String somme=rs.getString("sum(quantite)");
                    txt_somme.setText(somme);
                }
              
              
            } catch (SQLException ex) {
                Logger.getLogger(fenetre_principale.class.getName()).log(Level.SEVERE, null, ex);
            }
    montrer_produits_dans_JTable();
    }//GEN-LAST:event_btn_sommeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetre_principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable_Produits;
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_choisir_image;
    private javax.swing.JButton btn_debut;
    private javax.swing.JButton btn_fin;
    private javax.swing.JButton btn_maj;
    private javax.swing.JButton btn_precedent;
    private javax.swing.JButton btn_somme;
    private javax.swing.JButton btn_suivant;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_image;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prix;
    private javax.swing.JTextField txt_quantite;
    private javax.swing.JTextField txt_somme;
    // End of variables declaration//GEN-END:variables
}
